# =============================================================================
# Bead 6.2: cert-manager Helm Release
# =============================================================================
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.14.x"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Install CRDs
    installCRDs: true

    # Replicas for HA
    replicaCount: 2

    # Service account with IRSA annotation
    serviceAccount:
      create: true
      name: cert-manager
      annotations:
        # This ARN will be replaced with actual value from Terraform output
        eks.amazonaws.com/role-arn: "${CERT_MANAGER_ROLE_ARN}"

    # Resource limits
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Webhook configuration
    webhook:
      replicaCount: 2
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # CA Injector
    cainjector:
      replicaCount: 2
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

    # Prometheus metrics
    prometheus:
      enabled: true
      servicemonitor:
        enabled: false
