# =============================================================================
# Bead 8.2 & 8.3: Customer1 SecretProviderClass for AWS Secrets Manager
# =============================================================================
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: customer1-secrets
  namespace: customer1
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "customer1-db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
  # Sync to Kubernetes Secret for apps that need env vars
  secretObjects:
    - secretName: customer1-db-credentials
      type: Opaque
      data:
        - objectName: db-username
          key: username
        - objectName: db-password
          key: password
---
# =============================================================================
# Test Pod for Secrets Verification (Bead 8.2 Test)
# =============================================================================
# Uncomment to test secrets integration
# apiVersion: v1
# kind: Pod
# metadata:
#   name: secrets-test
#   namespace: customer1
# spec:
#   serviceAccountName: customer1-sa
#   containers:
#     - name: test
#       image: busybox:1.36
#       command: ["sleep", "3600"]
#       volumeMounts:
#         - name: secrets
#           mountPath: /mnt/secrets
#           readOnly: true
#   volumes:
#     - name: secrets
#       csi:
#         driver: secrets-store.csi.k8s.io
#         readOnly: true
#         volumeAttributes:
#           secretProviderClass: customer1-secrets
