# =============================================================================
# Bead 4.1: Secrets Store CSI Driver Helm Release
# =============================================================================
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.4.x"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
      interval: 12h
  values:
    # Enable syncing secrets to Kubernetes secrets
    syncSecret:
      enabled: true
    # Enable secret rotation
    enableSecretRotation: true
    rotationPollInterval: "2m"
    # Resource limits
    linux:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 200Mi
