# =============================================================================
# Bead 12.2: CloudWatch Container Insights - Fluent Bit Logs
# =============================================================================
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-for-fluent-bit
  namespace: amazon-cloudwatch
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-for-fluent-bit
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
      interval: 12h
  values:
    serviceAccount:
      create: true
      name: fluent-bit
      annotations:
        # This ARN will be replaced with actual value from Terraform output
        eks.amazonaws.com/role-arn: "${CLOUDWATCH_ROLE_ARN}"

    cloudWatch:
      enabled: true
      region: eu-west-1
      logGroupName: /aws/eks/mercury-eks-staging/containers
      logRetentionDays: 30
      autoCreateGroup: true

    kinesis:
      enabled: false

    firehose:
      enabled: false

    elasticsearch:
      enabled: false

    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi

    # Tolerations to run on all nodes
    tolerations:
      - operator: Exists

    # Input configuration
    input:
      tag: "kube.*"
      path: "/var/log/containers/*.log"
      parser: "docker"
      memBufLimit: "5MB"
      skipLongLines: "On"
      refreshInterval: "10"
