# =============================================================================
# Bead 12.1: CloudWatch Container Insights - Metrics
# =============================================================================
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-cloudwatch-metrics
  namespace: amazon-cloudwatch
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-cloudwatch-metrics
      version: "0.0.x"
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
      interval: 12h
  values:
    clusterName: mercury-eks-staging

    serviceAccount:
      create: true
      name: cloudwatch-agent
      annotations:
        # This ARN will be replaced with actual value from Terraform output
        eks.amazonaws.com/role-arn: "${CLOUDWATCH_ROLE_ARN}"

    # Resource limits
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 400m
        memory: 400Mi

    # Tolerations to run on all nodes
    tolerations:
      - operator: Exists
